version: "3.7"
services:
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backend-network
        environment: 
            - MYSQL_DATABASE=example
            - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
    app:
        build: app
        restart: always
        secrets:
            - db-password  
        volumes:                     # mount volume on build for faster debugging
            - ./app/src:/src
        ports:
            - 3000:3000
        networks:
            - backend-network
            - frontend-network
    web:
        build: web
        restart: always
        ports:
            - 8090:80
        networks:
            - frontend-network

volumes:
    db-data:
secrets:
    db-password:
        file: db/password.txt
networks:
    backend-network:
    frontend-network: